"""
Streamlit dashboard for multi-country wildfire risk visualization.

Reads data/gold/gold_test_predictions.csv (generated by the pipeline).
Launch: python -m streamlit run dashboard/app.py
"""
from __future__ import annotations

import os
from pathlib import Path

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st
from dotenv import load_dotenv
from google import genai

ROOT = Path(__file__).resolve().parents[1]
load_dotenv(ROOT / ".env")

# ── Page config ──────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Wildfire Risk Dashboard",
    page_icon="🔥",
    layout="wide",
    initial_sidebar_state="expanded",
)

REGION_COLORS = {
    "Portugal": "#006847",
    "California (USA)": "#B22234",
    "Southeast Australia": "#FFCD00",
}
MODEL_LABELS = {
    "XGB": "XGBoost",
    "RF": "Random Forest",
    "LR": "Logistic Regression",
}
RISK_SCALE = ["#1a9850", "#91cf60", "#fee08b", "#fc8d59", "#d73027"]

st.markdown(
    """
<style>
    @import url('https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,400;0,9..40,500;0,9..40,600;0,9..40,700;1,9..40,400&display=swap');

    html, body, [class*="css"] {
        font-family: 'DM Sans', sans-serif;
    }

    .stApp {
        background: linear-gradient(180deg, #f0f2f6 0%, #e8ecf1 100%);
    }

    /* Hero banner */
    .hero {
        background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%);
        border-radius: 16px;
        padding: 2rem 2.5rem;
        margin-bottom: 1.5rem;
        color: #ffffff;
        box-shadow: 0 8px 32px rgba(15, 52, 96, 0.25);
    }
    .hero h1 {
        font-size: 2rem;
        font-weight: 700;
        margin: 0 0 0.5rem 0;
        letter-spacing: -0.02em;
    }
    .hero p {
        font-size: 1.05rem;
        opacity: 0.88;
        margin: 0;
        line-height: 1.5;
    }
    .hero-badge {
        display: inline-block;
        background: rgba(255, 87, 34, 0.25);
        border: 1px solid rgba(255, 152, 0, 0.5);
        color: #ffab91;
        padding: 0.25rem 0.75rem;
        border-radius: 999px;
        font-size: 0.78rem;
        font-weight: 600;
        margin-top: 1rem;
        letter-spacing: 0.04em;
        text-transform: uppercase;
    }

    /* KPI cards */
    div[data-testid="stMetric"] {
        background: #ffffff;
        border-radius: 12px;
        padding: 1rem 1.25rem;
        box-shadow: 0 2px 12px rgba(0,0,0,0.06);
        border: 1px solid rgba(0,0,0,0.04);
    }
    div[data-testid="stMetricLabel"] {
        font-size: 0.82rem !important;
        font-weight: 600 !important;
        color: #5c6370 !important;
        text-transform: uppercase;
        letter-spacing: 0.04em;
    }
    div[data-testid="stMetricValue"] {
        font-size: 1.85rem !important;
        font-weight: 700 !important;
        color: #1a1a2e !important;
    }

    /* Sidebar */
    section[data-testid="stSidebar"] {
        background: linear-gradient(180deg, #1a1a2e 0%, #16213e 100%);
    }
    section[data-testid="stSidebar"] * {
        color: #e8eaed !important;
    }
    section[data-testid="stSidebar"] .stSlider label,
    section[data-testid="stSidebar"] .stSelectbox label,
    section[data-testid="stSidebar"] .stMultiSelect label {
        color: #b0bec5 !important;
        font-weight: 600;
        font-size: 0.8rem;
        text-transform: uppercase;
        letter-spacing: 0.05em;
    }
    section[data-testid="stSidebar"] hr {
        border-color: rgba(255,255,255,0.12);
    }

    /* Tabs */
    .stTabs [data-baseweb="tab-list"] {
        gap: 8px;
        background: transparent;
    }
    .stTabs [data-baseweb="tab"] {
        background: #ffffff;
        border-radius: 10px 10px 0 0;
        padding: 0.6rem 1.4rem;
        font-weight: 600;
        box-shadow: 0 -2px 8px rgba(0,0,0,0.04);
    }
    .stTabs [aria-selected="true"] {
        background: #ffffff !important;
        color: #e65100 !important;
        border-bottom: 3px solid #e65100 !important;
    }

    /* Section cards */
    .section-card {
        background: #ffffff;
        border-radius: 14px;
        padding: 1.5rem;
        box-shadow: 0 2px 16px rgba(0,0,0,0.05);
        border: 1px solid rgba(0,0,0,0.04);
        margin-bottom: 1rem;
    }

    /* Hide Streamlit footer */
    footer { visibility: hidden; }
    #MainMenu { visibility: hidden; }
</style>
""",
    unsafe_allow_html=True,
)


# ── Data loaders (cached) ────────────────────────────────────────────────────
@st.cache_data(show_spinner=False)
def load_predictions() -> pd.DataFrame:
    path = ROOT / "data" / "gold" / "gold_test_predictions.csv"
    if not path.exists():
        return pd.DataFrame()

    df = pd.read_csv(path)
    if "obs_date" in df.columns:
        df["obs_date"] = pd.to_datetime(df["obs_date"]).dt.date

    if "region_label" in df.columns:
        df["region"] = df["region_label"]
    elif "country" in df.columns:
        df["region"] = df["country"].str.replace("_", " ").str.title()
    else:
        df["region"] = "Unknown"

    for col in [c for c in df.columns if c.endswith("_prob")]:
        df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0).clip(0, 1)

    return df


@st.cache_data(show_spinner=False)
def load_model_results() -> pd.DataFrame:
    path = ROOT / "data" / "gold" / "gold_model_results.csv"
    if not path.exists():
        return pd.DataFrame()
    return pd.read_csv(path)


@st.cache_data(show_spinner=False)
def aggregate_timeseries(sub_df: pd.DataFrame, prob_col: str) -> pd.DataFrame:
    return (
        sub_df.groupby(["obs_date", "region"], as_index=False)[prob_col]
        .mean()
        .sort_values("obs_date")
    )


def risk_label(pct: float, threshold: float) -> str:
    if pct >= threshold:
        return "High"
    if pct >= threshold * 0.5:
        return "Moderate"
    return "Low"


def risk_color(label: str) -> str:
    return {"High": "#d73027", "Moderate": "#fc8d59", "Low": "#1a9850"}.get(label, "#5c6370")


def build_map_figure(map_df: pd.DataFrame, prob_col: str, region: str | None = None) -> go.Figure:
    title = f"Fire risk — {region}" if region else "Fire risk map"
    fig = px.scatter_mapbox(
        map_df,
        lat="latitude",
        lon="longitude",
        color=prob_col,
        size=prob_col,
        size_max=14,
        color_continuous_scale=RISK_SCALE,
        range_color=[0, 1],
        hover_name="region",
        hover_data={
            prob_col: ":.1%",
            "y_true": True,
            "latitude": False,
            "longitude": False,
        },
        mapbox_style="carto-darkmatter",
        zoom=4.5,
        center={"lat": map_df["latitude"].mean(), "lon": map_df["longitude"].mean()},
        title=title,
    )
    fires = map_df[map_df["y_true"] == 1]
    if len(fires):
        fig.add_trace(
            go.Scattermapbox(
                lat=fires["latitude"],
                lon=fires["longitude"],
                mode="markers",
                marker=dict(size=14, color="#ffffff", symbol="circle"),
                name="Confirmed fire",
                hovertemplate="Confirmed fire<extra></extra>",
            )
        )
    fig.update_layout(
        margin=dict(l=0, r=0, t=36, b=0),
        height=480,
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="rgba(0,0,0,0)",
        coloraxis_colorbar=dict(title="Risk", tickformat=".0%", len=0.85),
        legend=dict(orientation="h", y=1.02, x=0),
    )
    fig.update_traces(marker=dict(opacity=0.85))
    return fig


def build_timeline_figure(agg_df: pd.DataFrame, prob_col: str) -> go.Figure:
    fig = px.area(
        agg_df,
        x="obs_date",
        y=prob_col,
        color="region",
        color_discrete_map=REGION_COLORS,
        labels={"obs_date": "Date", prob_col: "Mean fire probability", "region": "Region"},
        template="plotly_white",
        line_shape="spline",
    )
    fig.update_layout(
        yaxis=dict(tickformat=".0%", range=[0, None]),
        hovermode="x unified",
        height=380,
        margin=dict(l=0, r=0, t=24, b=0),
        legend=dict(orientation="h", yanchor="bottom", y=1.02, x=0),
        paper_bgcolor="rgba(0,0,0,0)",
        plot_bgcolor="#fafbfc",
    )
    fig.update_traces(opacity=0.75)
    return fig


def build_region_comparison(sub_df: pd.DataFrame, prob_col: str) -> go.Figure:
    summary = (
        sub_df.groupby("region")
        .agg(
            avg_risk=(prob_col, "mean"),
            max_risk=(prob_col, "max"),
            fires=("y_true", "sum"),
        )
        .reset_index()
        .sort_values("avg_risk", ascending=True)
    )
    fig = px.bar(
        summary,
        x="avg_risk",
        y="region",
        orientation="h",
        color="region",
        color_discrete_map=REGION_COLORS,
        text=summary["avg_risk"].apply(lambda x: f"{x:.1%}"),
        labels={"avg_risk": "Average risk", "region": ""},
    )
    fig.update_traces(textposition="outside")
    fig.update_layout(
        showlegend=False,
        height=260,
        margin=dict(l=0, r=40, t=16, b=0),
        xaxis=dict(tickformat=".0%"),
        paper_bgcolor="rgba(0,0,0,0)",
    )
    return fig


# ── Load data ────────────────────────────────────────────────────────────────
df = load_predictions()
model_results = load_model_results()

# ── Sidebar ──────────────────────────────────────────────────────────────────
with st.sidebar:
    st.markdown("## 🔥 Wildfire MLOps")
    st.caption("Master's thesis · Multi-country pipeline")

    if df.empty:
        st.error("No predictions found. Run the pipeline first.")
        st.stop()

    st.markdown("---")
    st.markdown("**Filters**")

    regions_available = sorted(df["region"].dropna().unique())
    selected_regions = st.multiselect(
        "Regions",
        options=regions_available,
        default=regions_available,
        help="Select one or more countries to compare.",
    )

    model_map = {"XGBoost": "XGB", "Random Forest": "RF", "Logistic Regression": "LR"}
    selected_model_label = st.selectbox("Model", list(model_map.keys()), index=0)
    selected_model = model_map[selected_model_label]
    prob_col = f"{selected_model}_prob"

    risk_threshold = st.slider(
        "High-risk threshold",
        min_value=5,
        max_value=50,
        value=15,
        step=5,
        format="%d%%",
    )

    dates_available = sorted(df["obs_date"].dropna().unique())
    selected_date = st.select_date(
        "Map date",
        value=dates_available[-1],
        min_value=dates_available[0],
        max_value=dates_available[-1],
        help="Pick a date to inspect spatial risk.",
    )

    st.markdown("---")
    st.markdown("**Assistant**")
    if "messages" not in st.session_state:
        st.session_state.messages = []

    chat_box = st.container(height=220)
    with chat_box:
        for msg in st.session_state.messages[-6:]:
            with st.chat_message(msg["role"]):
                st.markdown(msg["content"])

    if prompt := st.chat_input("Ask about the project…"):
        st.session_state.messages.append({"role": "user", "content": prompt})
        api_key = os.environ.get("GEMINI_API_KEY")
        if not api_key:
            reply = "Set `GEMINI_API_KEY` in `.env` to enable the assistant."
        else:
            try:
                client = genai.Client(api_key=api_key)
                system = (
                    "You assist users of a wildfire MLOps dashboard (Portugal, California, Australia). "
                    "Data: MODIS, ERA5-Land, FIRMS via GEE. Models: XGBoost, RF, LR. "
                    "Medallion pipeline. Answer briefly and professionally."
                )
                history = "\n".join(f"{m['role']}: {m['content']}" for m in st.session_state.messages[:-1])
                resp = client.models.generate_content(
                    model="gemini-2.5-flash",
                    contents=f"{history}\nUser: {prompt}",
                    config={"system_instruction": system},
                )
                reply = resp.text
            except Exception as exc:
                reply = f"Assistant error: {exc}"
        st.session_state.messages.append({"role": "assistant", "content": reply})
        st.rerun()

# ── Main content ─────────────────────────────────────────────────────────────
date_min, date_max = df["obs_date"].min(), df["obs_date"].max()
fire_total = int((df["y_true"] == 1).sum())
elevated = int((df[prob_col] >= risk_threshold / 100).sum()) if prob_col in df.columns else 0

st.markdown(
    f"""
<div class="hero">
  <h1>Wildfire Risk Dashboard</h1>
  <p>Real satellite-driven 7-day fire probability across Portugal, California &amp; Southeast Australia<br>
  <strong>{date_min}</strong> → <strong>{date_max}</strong> · GEE + MODIS + ERA5 + FIRMS</p>
  <span class="hero-badge">Live pipeline output</span>
</div>
""",
    unsafe_allow_html=True,
)

k1, k2, k3, k4, k5 = st.columns(5)
k1.metric("Predictions", f"{len(df):,}")
k2.metric("Regions", df["region"].nunique())
k3.metric("Confirmed fires", fire_total)
k4.metric("Elevated alerts", elevated, help=f"Probability ≥ {risk_threshold}%")
best_pr = "—"
if not model_results.empty and "pr_auc" in model_results.columns:
    best = model_results.loc[model_results["pr_auc"].idxmax()]
    best_pr = f"{best['model_name']} · {best['pr_auc']:.2f}"
k5.metric("Best PR-AUC", best_pr)

tab_map, tab_research = st.tabs(["🗺️ Risk Analytics", "📊 Research Findings"])

sub_df = df[df["region"].isin(selected_regions)] if selected_regions else df.iloc[0:0]

with tab_map:
    if sub_df.empty or prob_col not in sub_df.columns:
        st.warning("Select at least one region to view analytics.")
    else:
        map_df = sub_df[sub_df["obs_date"] == selected_date].copy()
        agg_df = aggregate_timeseries(sub_df, prob_col)
        latest_agg = agg_df[agg_df["obs_date"] == selected_date]

        st.markdown("#### Snapshot")
        metric_cols = st.columns(min(len(selected_regions), 4))
        for i, region in enumerate(selected_regions[:4]):
            row = latest_agg[latest_agg["region"] == region]
            pct = float(row[prob_col].iloc[0]) * 100 if len(row) else 0.0
            label = risk_label(pct, risk_threshold)
            with metric_cols[i]:
                st.metric(
                    region.split("(")[0].strip(),
                    f"{pct:.1f}%",
                    delta=label,
                    delta_color="inverse" if label == "High" else "off",
                )

        left, right = st.columns([1.35, 1])
        with left:
            st.markdown("#### Spatial risk map")
            if map_df.empty:
                st.info("No data for the selected date.")
            else:
                fires_today = int((map_df["y_true"] == 1).sum())
                if fires_today:
                    st.error(f"🔥 {fires_today} confirmed fire event(s) on **{selected_date}**")
                else:
                    st.success(f"No confirmed fires on **{selected_date}** in selection.")
                # Cap map points for smooth rendering
                display_map = map_df.nlargest(min(len(map_df), 1500), prob_col)
                st.plotly_chart(
                    build_map_figure(display_map, prob_col),
                    use_container_width=True,
                    config={"displayModeBar": False},
                )

        with right:
            st.markdown("#### Region comparison")
            st.plotly_chart(
                build_region_comparison(sub_df, prob_col),
                use_container_width=True,
                config={"displayModeBar": False},
            )
            st.markdown("#### Top risk cells")
            top = (
                sub_df.nlargest(8, prob_col)[["obs_date", "region", prob_col, "y_true"]]
                .rename(columns={prob_col: "risk", "y_true": "fire"})
            )
            top["risk"] = top["risk"].apply(lambda x: f"{x:.1%}")
            top["fire"] = top["fire"].map({1: "✓", 0: "—"})
            st.dataframe(top, hide_index=True, use_container_width=True)

        st.markdown("#### Risk trend over time")
        st.plotly_chart(
            build_timeline_figure(agg_df, prob_col),
            use_container_width=True,
            config={"displayModeBar": False},
        )

with tab_research:
    st.markdown("#### Thesis research questions")
    st.caption("Figures and tables generated automatically from the latest pipeline run.")

    rq_summaries = {
        "rq1": ("Pipeline architecture", "Medallion design: GEE → Bronze → Silver → Gold → Dashboard."),
        "rq2": ("Multi-source fusion", "Combined vegetation + weather beats single-source baselines."),
        "rq3": ("Feature importance", "Seasonality, EVI, and weather lags drive predictions."),
        "rq4": ("Class imbalance", "Class weighting reduces false negatives on rare fire events."),
        "rq5": ("Model comparison", "XGBoost, Random Forest, and Logistic Regression benchmarked."),
        "rq6": ("Orchestration", "Airflow DAG chains all pipeline steps for reproducibility."),
        "rq7": ("Decision support", "Interactive maps translate model scores into actionable risk."),
    }

    figures_dir = ROOT / "outputs" / "figures"
    tables_dir = ROOT / "outputs" / "tables"

    if not figures_dir.exists():
        st.warning("Run step 5 of the pipeline to generate thesis figures.")
    else:
        cols = st.columns(2)
        for idx, rq in enumerate(sorted(rq_summaries.keys())):
            title, blurb = rq_summaries[rq]
            with cols[idx % 2]:
                with st.container(border=True):
                    st.markdown(f"**{rq.upper()} · {title}**")
                    st.caption(blurb)

                    rq_fig = figures_dir / rq
                    pngs = sorted(rq_fig.glob("*.png")) if rq_fig.exists() else []
                    if pngs:
                        st.image(str(pngs[0]), use_container_width=True)
                    else:
                        pdfs = sorted(rq_fig.glob("*.pdf")) if rq_fig.exists() else []
                        if pdfs:
                            st.caption(f"Figure: `{pdfs[0].name}`")

                    rq_tbl = tables_dir / rq
                    if rq_tbl.exists():
                        csvs = sorted(rq_tbl.glob("*.csv"))
                        if csvs:
                            tbl = pd.read_csv(csvs[0])
                            st.dataframe(tbl, hide_index=True, use_container_width=True, height=160)

        report_path = ROOT / "outputs" / "reports" / "research_question_answers.md"
        if report_path.exists():
            with st.expander("📄 Full research summary report"):
                st.markdown(report_path.read_text(encoding="utf-8"))
