"""
Streamlit dashboard for multi-country wildfire risk visualization.

Author: Anandhu R Krishnan
Reads:  data/gold/gold_test_predictions.csv (generated by the pipeline)
Launch: python -m streamlit run dashboard/app.py
"""
from __future__ import annotations

import os
from pathlib import Path

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st
from dotenv import load_dotenv
from google import genai

ROOT = Path(__file__).resolve().parents[1]
GOLD = ROOT / "data" / "gold"
load_dotenv(ROOT / ".env")

st.set_page_config(
    page_title="Wildfire Risk Dashboard",
    page_icon="🔥",
    layout="wide",
    initial_sidebar_state="expanded",
)

REGION_COLORS = {
    "Portugal": "#006847",
    "California (USA)": "#B22234",
    "Southeast Australia": "#FFCD00",
}
REGION_VIEW = {
    "Portugal": {"lat": 39.5, "lon": -8.0, "zoom": 6},
    "California (USA)": {"lat": 38.2, "lon": -120.0, "zoom": 5.2},
    "Southeast Australia": {"lat": -36.5, "lon": 146.0, "zoom": 5.5},
}
RISK_SCALE = ["#1a9850", "#91cf60", "#fee08b", "#fc8d59", "#d73027"]

# Readable dark text on all Plotly charts
CHART_FONT = dict(family="DM Sans, sans-serif", color="#1a1a2e", size=13)
CHART_LAYOUT = dict(
    font=CHART_FONT,
    title_font=dict(color="#1a1a2e", size=15),
    paper_bgcolor="#ffffff",
    plot_bgcolor="#fafbfc",
)

st.markdown(
    """
<style>
    @import url('https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;600;700&display=swap');

    html, body, [class*="css"] {
        font-family: 'DM Sans', sans-serif;
        color: #1a1a2e;
    }

    .stApp {
        background: linear-gradient(180deg, #f5f7fa 0%, #eef1f5 100%);
        color: #1a1a2e;
    }

    /* Main area — headings and body text */
    .main .block-container { color: #1a1a2e; }
    .main h1, .main h2, .main h3, .main h4, .main h5, .main h6,
    .main p, .main li, .main span, .main label {
        color: #1a1a2e !important;
    }
    .main .stCaption { color: #455a64 !important; }

    /* Hero — white text on dark background */
    .hero {
        background: linear-gradient(135deg, #1a1a2e 0%, #16213e 50%, #0f3460 100%);
        border-radius: 16px;
        padding: 2rem 2.5rem;
        margin-bottom: 1.5rem;
        box-shadow: 0 8px 32px rgba(15, 52, 96, 0.25);
    }
    .hero h1 {
        font-size: 2rem;
        font-weight: 700;
        margin: 0 0 0.5rem 0;
        color: #ffffff !important;
    }
    .hero p {
        font-size: 1.05rem;
        margin: 0;
        line-height: 1.5;
        color: #e3f2fd !important;
    }
    .hero-badge {
        display: inline-block;
        margin-top: 1rem;
        padding: 0.25rem 0.75rem;
        border-radius: 999px;
        font-size: 0.78rem;
        font-weight: 600;
        background: rgba(255, 152, 0, 0.2);
        border: 1px solid #ffb74d;
        color: #ffe0b2 !important;
        text-transform: uppercase;
        letter-spacing: 0.04em;
    }

    /* KPI cards */
    div[data-testid="stMetric"] {
        background: #ffffff;
        border-radius: 12px;
        padding: 1rem 1.25rem;
        box-shadow: 0 2px 12px rgba(0,0,0,0.06);
        border: 1px solid #e0e0e0;
    }
    div[data-testid="stMetricLabel"] {
        font-size: 0.82rem !important;
        font-weight: 600 !important;
        color: #546e7a !important;
        text-transform: uppercase;
    }
    div[data-testid="stMetricValue"] {
        font-size: 1.75rem !important;
        font-weight: 700 !important;
        color: #1a1a2e !important;
    }
    div[data-testid="stMetricDelta"] {
        font-weight: 600 !important;
        color: #546e7a !important;
    }
    div[data-testid="stMetricDelta"] svg {
        fill: #546e7a !important;
    }

    /* Light sidebar — dark readable text */
    section[data-testid="stSidebar"] {
        background: #ffffff !important;
        border-right: 1px solid #e0e0e0;
    }
    section[data-testid="stSidebar"] .block-container { color: #1a1a2e !important; }
    section[data-testid="stSidebar"] h1,
    section[data-testid="stSidebar"] h2,
    section[data-testid="stSidebar"] h3,
    section[data-testid="stSidebar"] p,
    section[data-testid="stSidebar"] label,
    section[data-testid="stSidebar"] span,
    section[data-testid="stSidebar"] .stMarkdown {
        color: #1a1a2e !important;
    }
    section[data-testid="stSidebar"] .stCaption { color: #546e7a !important; }
    section[data-testid="stSidebar"] hr { border-color: #e0e0e0; }

    /* Tabs */
    .stTabs [data-baseweb="tab"] {
        background: #ffffff;
        color: #546e7a !important;
        font-weight: 600;
        border: 1px solid #e0e0e0;
        border-bottom: none;
        border-radius: 8px 8px 0 0;
    }
    .stTabs [aria-selected="true"] {
        color: #e65100 !important;
        border-bottom: 3px solid #e65100 !important;
    }

    /* Research expanders */
    .streamlit-expanderHeader {
        color: #1a1a2e !important;
        font-weight: 600 !important;
        background: #ffffff !important;
    }
    .streamlit-expanderContent {
        color: #1a1a2e !important;
        background: #fafbfc !important;
    }

    footer, #MainMenu { visibility: hidden; }
</style>
""",
    unsafe_allow_html=True,
)


@st.cache_data(show_spinner=False)
def load_predictions() -> pd.DataFrame:
    path = GOLD / "gold_test_predictions.csv"
    if not path.exists():
        return pd.DataFrame()
    df = pd.read_csv(path)
    if "obs_date" in df.columns:
        df["obs_date"] = pd.to_datetime(df["obs_date"]).dt.date
    if "region_label" in df.columns:
        df["region"] = df["region_label"]
    elif "country" in df.columns:
        df["region"] = df["country"].str.replace("_", " ").str.title()
    else:
        df["region"] = "Unknown"
    for col in [c for c in df.columns if c.endswith("_prob")]:
        df[col] = pd.to_numeric(df[col], errors="coerce").fillna(0).clip(0, 1)
    return df


@st.cache_data(show_spinner=False)
def load_model_results() -> pd.DataFrame:
    path = GOLD / "gold_model_results.csv"
    return pd.read_csv(path) if path.exists() else pd.DataFrame()


@st.cache_data(show_spinner=False)
def load_gold_csv(name: str) -> pd.DataFrame:
    path = GOLD / name
    return pd.read_csv(path) if path.exists() else pd.DataFrame()


@st.cache_data(show_spinner=False)
def aggregate_timeseries(sub_df: pd.DataFrame, prob_col: str) -> pd.DataFrame:
    return (
        sub_df.groupby(["obs_date", "region"], as_index=False)[prob_col]
        .mean()
        .sort_values("obs_date")
    )


def risk_label(pct: float, threshold: float) -> str:
    if pct >= threshold:
        return "High"
    if pct >= threshold * 0.5:
        return "Moderate"
    return "Low"


def map_center_for_region(region: str, map_df: pd.DataFrame) -> dict:
    """Use fixed country viewport so multi-region selections don't drift to West Africa."""
    if region in REGION_VIEW:
        return REGION_VIEW[region]
    return {
        "lat": float(map_df["latitude"].mean()),
        "lon": float(map_df["longitude"].mean()),
        "zoom": 5,
    }


def build_map_figure(map_df: pd.DataFrame, prob_col: str, region: str) -> go.Figure:
    view = map_center_for_region(region, map_df)
    fig = px.scatter_mapbox(
        map_df,
        lat="latitude",
        lon="longitude",
        color=prob_col,
        size=prob_col,
        size_max=16,
        color_continuous_scale=RISK_SCALE,
        range_color=[0, max(0.05, float(map_df[prob_col].max()))],
        hover_name="region",
        hover_data={prob_col: ":.1%", "y_true": True, "latitude": False, "longitude": False},
        mapbox_style="carto-positron",
        zoom=view["zoom"],
        center={"lat": view["lat"], "lon": view["lon"]},
        title=f"{region}",
    )
    fires = map_df[map_df["y_true"] == 1]
    if len(fires):
        fig.add_trace(
            go.Scattermapbox(
                lat=fires["latitude"],
                lon=fires["longitude"],
                mode="markers",
                marker=dict(size=16, color="#c62828", symbol="circle"),
                name="Confirmed fire",
                hovertemplate="Confirmed fire<extra></extra>",
            )
        )
    fig.update_layout(
        margin=dict(l=0, r=0, t=40, b=0),
        height=420,
        coloraxis_colorbar=dict(
            title=dict(text="Risk", font=dict(color="#1a1a2e", size=12)),
            tickformat=".0%",
            tickfont=dict(color="#1a1a2e", size=11),
        ),
        title_font=dict(color="#1a1a2e", size=15),
        font=CHART_FONT,
    )
    return fig


def build_timeline_figure(agg_df: pd.DataFrame, prob_col: str) -> go.Figure:
    ymax = max(float(agg_df[prob_col].max()) * 1.25, 0.05)
    fig = px.area(
        agg_df,
        x="obs_date",
        y=prob_col,
        color="region",
        color_discrete_map=REGION_COLORS,
        labels={"obs_date": "Date", prob_col: "Mean probability", "region": "Region"},
        template="plotly_white",
        line_shape="spline",
    )
    fig.update_layout(
        title="Mean predicted fire probability over time by region",
        yaxis=dict(
            tickformat=".1%",
            range=[0, ymax],
            tickfont=dict(color="#37474f"),
            title=dict(font=dict(color="#1a1a2e")),
        ),
        xaxis=dict(tickfont=dict(color="#37474f"), title=dict(font=dict(color="#1a1a2e"))),
        hovermode="x unified",
        height=360,
        legend=dict(orientation="h", y=1.08, x=0, font=dict(color="#1a1a2e")),
        **CHART_LAYOUT,
    )
    return fig


def build_region_comparison(sub_df: pd.DataFrame, prob_col: str) -> go.Figure:
    summary = (
        sub_df.groupby("region")
        .agg(avg_risk=(prob_col, "mean"), fires=("y_true", "sum"))
        .reset_index()
        .sort_values("avg_risk", ascending=True)
    )
    fig = px.bar(
        summary,
        x="avg_risk",
        y="region",
        orientation="h",
        color="region",
        color_discrete_map=REGION_COLORS,
        text=summary["avg_risk"].apply(lambda x: f"{x:.2%}"),
        labels={"avg_risk": "Average probability", "region": ""},
    )
    fig.update_traces(textposition="outside")
    fig.update_layout(
        title="Average predicted risk by region (test set)",
        showlegend=False,
        height=240,
        xaxis=dict(
            tickformat=".1%",
            tickfont=dict(color="#37474f"),
            title=dict(font=dict(color="#1a1a2e")),
        ),
        yaxis=dict(tickfont=dict(color="#37474f"), title=dict(font=dict(color="#1a1a2e"))),
        **CHART_LAYOUT,
    )
    return fig


def render_research_chart(rq: str) -> None:
    """Build thesis charts live from gold CSVs (no PNG dependency)."""
    if rq == "rq2":
        df = load_gold_csv("gold_ablation_rq2.csv")
        if df.empty:
            return
        fig = px.bar(
            df,
            x="dataset",
            y=["pr_auc", "f1_score"],
            barmode="group",
            labels={"value": "Score", "dataset": "Feature set", "variable": "Metric"},
            color_discrete_sequence=["#1565c0", "#e65100"],
            template="plotly_white",
        )
        fig.update_layout(title="RQ2 — Feature-set ablation (PR-AUC vs F1)", **CHART_LAYOUT)
        st.plotly_chart(fig, use_container_width=True, config={"displayModeBar": False})
    elif rq == "rq3":
        df = load_gold_csv("xgb_feature_importance.csv")
        if df.empty:
            return
        fig = px.bar(
            df.head(8),
            x="importance",
            y="feature",
            orientation="h",
            color_discrete_sequence=["#2e7d32"],
            template="plotly_white",
        )
        fig.update_layout(title="RQ3 — XGBoost feature importance (top 8)", **CHART_LAYOUT)
        st.plotly_chart(fig, use_container_width=True, config={"displayModeBar": False})
    elif rq == "rq4":
        df = load_gold_csv("gold_imbalance_rq4.csv")
        if df.empty:
            return
        xgb = df[df["model_name"] == "XGB"]
        if xgb.empty:
            return
        fig = px.bar(
            xgb,
            x="imbalance_mode",
            y=["recall_score", "pr_auc"],
            barmode="group",
            labels={"value": "Score", "imbalance_mode": "Strategy"},
            template="plotly_white",
        )
        fig.update_layout(title="RQ4 — Class imbalance strategies (XGBoost)", **CHART_LAYOUT)
        st.plotly_chart(fig, use_container_width=True, config={"displayModeBar": False})
    elif rq == "rq5":
        df = load_gold_csv("gold_model_results.csv")
        if df.empty:
            return
        bal = df[df["imbalance_mode"] == "balanced"] if "imbalance_mode" in df.columns else df
        y_cols = ["pr_auc", "roc_auc"]
        if "f1_score_best_f1" in bal.columns:
            y_cols.append("f1_score_best_f1")
        else:
            y_cols.append("f1_score")
        fig = px.bar(
            bal,
            x="model_name",
            y=y_cols,
            barmode="group",
            labels={"value": "Score", "model_name": "Model", "variable": "Metric"},
            template="plotly_white",
        )
        fig.update_layout(title="RQ5 — Model comparison (PR-AUC primary; F1 at tuned threshold if available)", **CHART_LAYOUT)
        st.plotly_chart(fig, use_container_width=True, config={"displayModeBar": False})


# ── Data ─────────────────────────────────────────────────────────────────────
df = load_predictions()
model_results = load_model_results()

with st.sidebar:
    st.markdown("## 🔥 Wildfire MLOps")
    st.caption("Master's thesis · Multi-country pipeline")

    if df.empty:
        st.error("No predictions found. Run: `python src/pipeline_real.py --quick`")
        st.stop()

    st.markdown("---")
    st.markdown("**Filters**")

    regions_available = sorted(df["region"].dropna().unique())
    selected_regions = st.multiselect("Regions", regions_available, default=regions_available)

    model_map = {"XGBoost": "XGB", "Random Forest": "RF", "Logistic Regression": "LR"}
    selected_model = model_map[st.selectbox("Model", list(model_map.keys()))]
    prob_col = f"{selected_model}_prob"

    risk_threshold = st.slider("High-risk threshold", 5, 50, 15, 5, format="%d%%")

    dates_available = sorted(df["obs_date"].dropna().unique())
    date_labels = [str(d) for d in dates_available]
    selected_label = st.selectbox("Map date", date_labels, index=len(date_labels) - 1)
    selected_date = dates_available[date_labels.index(selected_label)]

    st.markdown("---")
    st.markdown("**Assistant**")
    if "messages" not in st.session_state:
        st.session_state.messages = []
    chat_box = st.container(height=200)
    with chat_box:
        for msg in st.session_state.messages[-6:]:
            with st.chat_message(msg["role"]):
                st.markdown(msg["content"])
    if prompt := st.chat_input("Ask about the project…"):
        st.session_state.messages.append({"role": "user", "content": prompt})
        api_key = os.environ.get("GEMINI_API_KEY")
        if not api_key:
            reply = "Set `GEMINI_API_KEY` in `.env` to enable the assistant."
        else:
            try:
                client = genai.Client(api_key=api_key)
                resp = client.models.generate_content(
                    model="gemini-2.5-flash",
                    contents=prompt,
                    config={
                        "system_instruction": (
                            "Brief wildfire MLOps thesis assistant. "
                            "Portugal, California, Australia. GEE, MODIS, ERA5, FIRMS. Models: XGB, RF, LR."
                        )
                    },
                )
                reply = resp.text
            except Exception as exc:
                reply = f"Error: {exc}"
        st.session_state.messages.append({"role": "assistant", "content": reply})
        st.rerun()

# ── Main ─────────────────────────────────────────────────────────────────────
date_min, date_max = df["obs_date"].min(), df["obs_date"].max()
fire_total = int((df["y_true"] == 1).sum())
elevated = int((df[prob_col] >= risk_threshold / 100).sum())

st.markdown(
    f"""
<div class="hero">
  <h1>Wildfire Risk Dashboard</h1>
  <p>Real satellite-driven 7-day fire probability · Portugal · California · Southeast Australia<br>
  <strong>{date_min}</strong> → <strong>{date_max}</strong> · GEE + MODIS + ERA5 + FIRMS</p>
  <span class="hero-badge">Live pipeline output</span>
</div>
""",
    unsafe_allow_html=True,
)

c1, c2, c3, c4, c5 = st.columns(5)
c1.metric("Predictions", f"{len(df):,}")
c2.metric("Regions", int(df["region"].nunique()))
c3.metric("Confirmed fires", fire_total)
c4.metric("Elevated alerts", elevated)
best_pr = "N/A"
best_pr_caption = ""
base_rate_pct = 100 * fire_total / max(len(df), 1)
if not model_results.empty and "pr_auc" in model_results.columns:
    bal = model_results
    if "imbalance_mode" in model_results.columns:
        bal = model_results[model_results["imbalance_mode"] == "balanced"]
    if not bal.empty:
        row = bal.loc[bal["pr_auc"].idxmax()]
        best_pr = f"{row['model_name']} ({row['pr_auc']:.3f})"
        best_pr_caption = (
            f"Test-set base rate ≈ {base_rate_pct:.1f}%. "
            "PR-AUC should exceed this random baseline — not approach 1.0 on rare events."
        )
c5.metric("Best PR-AUC vs base rate", best_pr)
if best_pr_caption:
    c5.caption(best_pr_caption)

tab_map, tab_research = st.tabs(["🗺️ Risk Analytics", "📊 Research Findings"])
sub_df = df[df["region"].isin(selected_regions)] if selected_regions else df.iloc[0:0]

with tab_map:
    if sub_df.empty or prob_col not in sub_df.columns:
        st.warning("Select at least one region.")
    else:
        agg_df = aggregate_timeseries(sub_df, prob_col)
        latest_agg = agg_df[agg_df["obs_date"] == selected_date]

        st.markdown("#### Snapshot")
        snap_cols = st.columns(len(selected_regions))
        for i, region in enumerate(selected_regions):
            row = latest_agg[latest_agg["region"] == region]
            pct = float(row[prob_col].iloc[0]) * 100 if len(row) else 0.0
            with snap_cols[i]:
                label = risk_label(pct, risk_threshold)
                st.metric(
                    region.split("(")[0].strip(),
                    f"{pct:.2f}%",
                )
                risk_color = {"High": "#c62828", "Moderate": "#ef6c00", "Low": "#2e7d32"}[label]
                st.markdown(
                    f'<p style="color:{risk_color};font-weight:600;margin:0;">{label} risk</p>',
                    unsafe_allow_html=True,
                )

        st.markdown("#### Spatial risk maps")
        map_tabs = st.tabs([r.split("(")[0].strip() for r in selected_regions])
        for tab, region in zip(map_tabs, selected_regions):
            with tab:
                region_map = sub_df[(sub_df["region"] == region) & (sub_df["obs_date"] == selected_date)]
                if region_map.empty:
                    st.info(f"No data for {region} on {selected_date}.")
                    continue
                fires_today = int((region_map["y_true"] == 1).sum())
                if fires_today:
                    st.error(f"🔥 {fires_today} confirmed fire(s) on {selected_date}")
                else:
                    st.success(f"No confirmed fires on {selected_date}")
                display = region_map.nlargest(min(len(region_map), 800), prob_col)
                st.plotly_chart(
                    build_map_figure(display, prob_col, region),
                    use_container_width=True,
                    config={"displayModeBar": False},
                )

        col_l, col_r = st.columns([1.2, 1])
        with col_l:
            st.markdown("#### Risk trend over time")
            st.plotly_chart(
                build_timeline_figure(agg_df, prob_col),
                use_container_width=True,
                config={"displayModeBar": False},
            )
        with col_r:
            st.markdown("#### Region comparison")
            st.plotly_chart(
                build_region_comparison(sub_df, prob_col),
                use_container_width=True,
                config={"displayModeBar": False},
            )
            st.markdown("#### Top risk cells")
            top = sub_df.nlargest(10, prob_col)[["obs_date", "region", prob_col, "y_true"]].copy()
            top[prob_col] = top[prob_col].map(lambda x: f"{x:.1%}")
            top["y_true"] = top["y_true"].map({1: "🔥 Yes", 0: "—"})
            top.columns = ["Date", "Region", "Risk", "Fire"]
            st.dataframe(top, hide_index=True, use_container_width=True)

with tab_research:
    st.markdown("#### Thesis research questions")
    st.caption("Charts built from pipeline outputs in `data/gold/`.")

    rq_info = {
        "rq1": "Pipeline architecture & latency",
        "rq2": "Multi-source fusion (NDVI + weather)",
        "rq3": "Feature importance (XGBoost)",
        "rq4": "Class imbalance strategies",
        "rq5": "Model comparison (LR / RF / XGB)",
        "rq6": "Orchestration & reproducibility",
        "rq7": "Decision support & risk scenarios",
    }
    tables_dir = ROOT / "outputs" / "tables"

    for rq, title in rq_info.items():
        with st.expander(f"**{rq.upper()}** — {title}", expanded=rq in ("rq2", "rq3", "rq5")):
            render_research_chart(rq)
            tbl_dir = tables_dir / rq
            if tbl_dir.exists():
                for csv_path in sorted(tbl_dir.glob("*.csv")):
                    st.markdown(f"**{csv_path.stem.replace('_', ' ').title()}**")
                    st.dataframe(pd.read_csv(csv_path), hide_index=True, use_container_width=True)

    report = ROOT / "outputs" / "reports" / "research_question_answers.md"
    if report.exists():
        with st.expander("📄 Full research summary"):
            st.markdown(report.read_text(encoding="utf-8"))
